name: Java Build

on:
  pull_request:
    branches:
      - "*"
if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'development'

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '14'

    - name: Build with Gradle
      run: |
        ./gradlew build

    - name: Run Java Program
      run: java -cp build/classes/java/main MainProgram

